### ISSUE TITLE
Impossible to run standalone or offline

### ISSUE THREAD

**Issue by flavienbwk** [pingcap/autoflow#399]
Hello,

I have a use case for autoflow where I want to run this project offline.

However, and even after [deploying a standalone version of TiDB with Autoflow](https://github.com/flavienbwk/autoflow-standalone?tab=readme-ov-file#very-quick-start), it appears Autoflow can't be run without TiDB Cloud Serverless because Pingcap [didn't opensource the VECTOR() type in TiDB](https://docs.pingcap.com/tidbcloud/vector-search-data-types).

Although I understand the commercial strategy, this makes this entire project not really open source (stated "open source GraphRAG" in documentation). At most, partially open-source.

What alternative do you recommend for this use case ?

Thank you,

**Comment by breezewish** [comment]
The minimal required open-source TiDB version is v8.4, could you try with that instead? For example:

```
tiup playground v8.4 --tag my_cluster
```

**Comment by Icemap** [comment]
Hi @flavienbwk, thanks for liking! Here is the document of the Vector for TiDB v8.4 https://docs.pingcap.com/tidb/v8.4/vector-search-data-types#vector-data-types .
It is possible to run offline, and fully open-source for sure.

**Comment by flavienbwk** [comment]
Thank you for your quick answer and the clarification! I confirm I can run migrations and start the project with the 8.4 version :heavy_check_mark: 

I have several other bugs with the current version on _main_ but I'll eventually open other issues. I'm closing this one.
