### ISSUE TITLE
请问下，这tool_choice 在每次请求chat/completion的时候，一定会放值吗

### ISSUE THREAD

**Issue by sykp241095** [pingcap/autoflow#458]
![Image](https://github.com/user-attachments/assets/bf6fa9c6-077b-4a1e-8cc9-71f66801f1b0)

The origin question is "请问下，这tool_choice 在每次请求chat/completion的时候，一定会放值吗", they are using vllm to serve LLM, and a low version vllm seems does't support this option, ptal @Icemap

**Comment by sykp241095** [comment]
“一定要放tool_choice 这个参数吗，我们的网关有校验逻辑”

**Comment by Icemap** [comment]
Fixed. https://github.com/pingcap/autoflow/pull/487
