### ISSUE TITLE
The link of upload files is broken in the chat view

### ISSUE THREAD

**Issue by Mini256** [pingcap/autoflow#466]
![Image](https://github.com/user-attachments/assets/9fa18a38-3bed-47ee-b3e3-90cf81966d77)

**Comment by 634750802** [comment]
Add a new endpoint for downloading uploaded files (KB level access control).

**Comment by 634750802** [comment]
> Viewable first and then downloadable?

YES

**Comment by sykp241095** [comment]
@Rutheniumlmw We can make its url download-able first.
