### ISSUE TITLE
bug: wrong recommended questions

### ISSUE THREAD

**Issue by sykp241095** [pingcap/autoflow#485]
Link: https://tidb.ai/c/0193af3d-2d2b-7364-b93f-07dbe0469775

![Image](https://github.com/user-attachments/assets/e4ced7e0-aedf-4112-a74f-c78f6d84e1f0)

**Comment by Icemap** [comment]
This API has already been optimized. But we cannot 100% avoid it. We can use this refresh button to make a new set of questions.
![Image](https://github.com/user-attachments/assets/c6cc8c92-dbcf-4dc0-91d4-c1f2acb00b1c)
