### ISSUE TITLE
Evaluation List API Enhancement

### ISSUE THREAD

**Issue by Icemap** [pingcap/autoflow#505]
Add filters:

- Keywords
~~- Semantic Similarity Range~~
~~- Factual Correctness~~

The Metrics cannot be a filter. It's using the python code rather than SQL to achieve.

**Comment by 634750802** [comment]
Why not filter on frontend if the api is not paginated?

**Comment by Icemap** [comment]
Now, we only have `/admin/evaluation/tasks/{evaluation_task_id}/items` API, which is not paginated. And will be paginated within this issue.
