### ISSUE TITLE
Refine evaluation spec API

### ISSUE THREAD

**Issue by 634750802** [pingcap/autoflow#514]
- `GET /api/v1/admin/evaluation/datasets/{id}`
- `GET /api/v1/admin/evaluation/dataset-items/{itemId}` 
- `GET /api/v1/admin/evaluation/tasks/{id}`
  Replaces original `summary` api, and add a new `summary` field to the returned object.

**Comment by Icemap** [comment]
https://github.com/pingcap/autoflow/pull/515 PTAL, added summary in `GET /api/v1/admin/evaluation/datasets/{id}`.
