### ISSUE TITLE
docs(evaluation): https://tidb.ai/docs/evaluation

### ISSUE THREAD

**Issue by sykp241095** [pingcap/autoflow#526]

**Comment by Icemap** [comment]
<img width="251" alt="Image" src="https://github.com/user-attachments/assets/42c900e3-da9d-4891-a064-50ddf4af21e3" />
<img width="692" alt="Image" src="https://github.com/user-attachments/assets/f5c6d454-04a9-4108-8072-0abedb879b66" />
<img width="668" alt="Image" src="https://github.com/user-attachments/assets/b8030ae5-0284-4255-a5b5-d55b00c294ed" />
<img width="1248" alt="Image" src="https://github.com/user-attachments/assets/21f9f366-dab7-4904-9693-e95c032fb441" />

https://github.com/pingcap/autoflow/pull/539
