### ISSUE TITLE
Update the LLM / Embedding models for Gitee AI

### ISSUE THREAD

**Issue by Mini256** [pingcap/autoflow#549]
Update the LLM / Embedding models for Gitee AI

https://github.com/pingcap/autoflow/blob/main/frontend/app/src/pages/docs/llm.mdx
https://github.com/pingcap/autoflow/blob/main/frontend/app/src/pages/docs/embedding-model.mdx

**Comment by Mini256** [comment]
@lc-soft Could you also update the document?

**Comment by lc-soft** [comment]
Ok, I'll do it.
